### PR TITLE
Specify height for KaTeX svg elements.

### PR DESCRIPTION
**Pull request by ian-r-rose**
Another possible fix for #117. How about this @gnestor?

### CODE REVIEW

**Comment by gnestor** [comment]
That worked! 👍

**Comment by ian-r-rose** [comment]
Great! I submitted a patch with this same fix upstream that just got merged, so they are onboard with it too. We can maybe make a patch release with this until they cut another release.

**Comment by gnestor** [comment]
Sounds good! Thanks @ian-r-rose!

**Comment by ian-r-rose** [comment]
I can publish a patch release today, or if you are already on it, that's cool too.

**Comment by ian-r-rose** [comment]
Hah, you are fast.

**Pull request merged**
