### PR TITLE
Upgrade to newest rendermime-interfaces

### PR DESCRIPTION
**Pull request by gnestor**

### CODE REVIEW

**Comment by gnestor** [comment]
@blink1073 Should I wait to merge this until jupyterlab 0.28.0 is released?

**Comment by blink1073** [comment]
Yep, I’ll merge this and publish the packages after the final release.

**Comment by gnestor** [comment]
Alrighty! Do we want to move json-extension and vdom-extension to jupyterlab before or after 0.28.0 release?

**Comment by blink1073** [comment]
I'd say after, to give us some time with them on master.

**Comment by blink1073** [comment]
Shipped.

**Pull request merged**
