### PR TITLE
Update to MathJax 3.1

### PR DESCRIPTION
**Pull request by jasongrout**
MathJax 3.1 now comes with a [safe mode](http://docs.mathjax.org/en/latest/options/safe.html). This updates and enables it.

### CODE REVIEW

**Comment by jasongrout** [comment]
@dpvc - if you have a second, would you be able to glance at how we are using MathJax 3 as a library to typeset the contents of an html node in JupyterLab, and let us know if we're doing something really wrong or not in the intended way? I tried to trace through the MathJax code enough to understand how to use MathJax as a library, and this seems to work, and I verified that the safe extension is actually being applied.

The file where we are using MathJax to create a function to typeset an html node is: https://github.com/jupyterlab/jupyter-renderers/blob/2e6bf4e9ee0bcbbc1e1678443669676bc7849c4f/packages/mathjax3-extension/src/index.ts

Thanks!

**Comment by jasongrout** [comment]
Now that MathJax 3.1 ships with a Safe extension, the only huge blocker to migrating core JLab to it is the [linebreaking](http://docs.mathjax.org/en/latest/output/linebreaks.html) extension. Hopefully that comes soon too. Thanks again for all your work on MathJax!

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by dpvc** [comment]
@jasongrout, sorry, I let this slip through the cracks.  What you have done is fine, but the lines

https://github.com/jupyterlab/jupyter-renderers/blob/2e6bf4e9ee0bcbbc1e1678443669676bc7849c4f/packages/mathjax3-extension/src/index.ts#L60-L66

have been packaged into a single function, now.  So you could do

```
    this._html.options.elements = [node];
    this._html.clear().render();
```

instead.  This might be better, since if we add any other functions, you will get them automatically.  Also, this approach will run the `renderActions`, which allows you to hook into MathJax's processing pipeline with additional functionality if you want.

**Comment by jasongrout** [comment]
@dpvc - thanks! I really like being able to delegate the pipeline to mathjax, but still have a possibility of hooking in. I'll make your change a different PR.

**Pull request merged**
