### PR TITLE
Initial version of a MathJax 3 (prerelease) extension.

### PR DESCRIPTION
**Pull request by jasongrout**
Don't merge yet - this doesn't work yet.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
I have pushed workarounds for mathjax/mathjax-v3#68 and mathjax/mathjax-v3#69. I suspect that neither of these are intended behavior.

This is still not quite working, as I have not figured out how to have webpack pick up the MathJax fonts in `mathjax2/css`. Ideas?

**Comment by jasongrout** [comment]
Latest commit seems to get things to render okay, but the font location is hardcoded, so it doesn't look that great. Since we can't directly influence the jlab webpack config, we can't put in the appropriate webpack redirections to handle the hardcoded fonts, so we'll have to wait on that one.

**Comment by ian-r-rose** [comment]
What made the setting of the document unnecessary?

**Comment by jasongrout** [comment]
I don't know. I just tried it again and it worked.

**Comment by jasongrout** [comment]
The fonts issue has had some work in MathJax, so I think it's ready to tackle getting the fonts to load again. See https://github.com/mathjax/mathjax-v3/issues/70#issuecomment-350590791

**Comment by ian-r-rose** [comment]
@jasongrout This is now working, with the caveat that we need to update the JupyterLab webpack config to pick up `.otf` fonts, which is used in one of the typefaces.

**Comment by ian-r-rose** [comment]
I am seeing some errors with the parsing of HTML, but I believe those to be MathJax3 bugs.

**Comment by ian-r-rose** [comment]
@jasongrout I've been keeping this more-or-less up to date. Now mathjax3 is in beta, and some of the rendering bugs we saw in earlier versions have been ironed out. I think this is probably ready to merge and publish.

**Comment by blink1073** [comment]
:+1:

**Pull request merged**
