### PR TITLE
Vega3 extension

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by gnestor** [comment]
Related to https://github.com/jupyterlab/jupyterlab/pull/4661

**Comment by gnestor** [comment]
@domoritz I see that vega4-extension was merged into jupyterlab. Is this ready to merge?

**Comment by domoritz** [comment]
Yes

**Comment by gnestor** [comment]
Thanks! In the future, it would be great if vega-embed could support multiple versions of vega and vega-lite vs. the implementations needing to do that plumbing. I know that the you and the vega team gave it a go and it proved to be too difficult, but it may be worth it in the long-run... 🤷‍♂️

**Comment by domoritz** [comment]
Vega-Embed does support different versions of Vega (3+) and Vega-Lite (2+).

**Comment by gnestor** [comment]
@domoritz Would it be possible to create a new package (e.g. `vega-embed-universal`) that depends on vega-embed and vega-embed-v2 and simply inspects the spec to determine which version of vega-embed should be used and then calls the appropriate `embed` function with the args? The current issue is that every app that uses vega-embed (jupyterlab, nteract, classic notebook, etc.) is required to do this.

**Comment by domoritz** [comment]
Can you elaborate? Vega-Embed supports all recent versions of Vega and Vega-Lite.

**Comment by gnestor** [comment]
Vega-embed doesn't support vega 2 or vega-lite 1, correct?

**Comment by domoritz** [comment]
You already have to install a separate extension. Why should we not just keep them around?

**Pull request merged**
