### PR TITLE
@jupyterlab/katex-extension. Add settings section.

### PR DESCRIPTION
**Pull request by AlbertHilb**
Add settings section to `katex-extension`.
For now, it contains just one entry, `macros`, a collection of custom  LaTeX macros.

Cheers

### CODE REVIEW

**Comment by AlbertHilb** [comment]
You are perfectly right @ian-r-rose! Now, it is way better.

**Comment by AlbertHilb** [comment]
Added! :-)

**Comment by ian-r-rose** [comment]
Thanks @AlbertHilb!

**Comment by ian-r-rose** [comment]
Published as `@jupyterlab/katex-extension@0.19.1`

**Pull request merged**
