### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jtpio**
- [x] Update `@jupyterlab` packages
- [x] Update dev dependencies
- [x] Move from `tslint` to `eslint`
- [x] Fix lint-staged config
- [x] Fix compilation issues

This will help fix some of the dependabot alerts.

### CODE REVIEW

**Comment by fcollonval** [comment]
There is an inconsistency in @lumino/widgets version (probably the extension is using a different one than jupyterlab). It needs to be updated in the dependencies too.

**Comment by jtpio** [comment]
OK this now seems to be building fine on CI.

**Comment by jtpio** [comment]
Rebased to get the changes from #270 so we can check on Binder: https://mybinder.org/v2/gh/jtpio/jupyter-renderers/update-deps?urlpath=lab/tree/notebooks

**Comment by jtpio** [comment]
Looking good on Binder:

image

**Review by fcollonval — APPROVED** [review]
Thanks a lot for this effort @jtpio

**Pull request merged**
