### PR TITLE
Add fasta-extension

### PR DESCRIPTION
**Pull request by gnestor**
Moving over from https://github.com/jupyterlab/jupyterlab-fasta

README: https://github.com/gnestor/jupyter-renderers/tree/fasta-extension/packages/fasta-extension

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks!

**Comment by gnestor** [comment]
I'm noticing a 3-4s lag when switching between tabs/panes that are rendering fasta. I tried doing a profile in Chrome Devtools and didn't see anything related to the MSA library being used here. Switching between tabs of say geojson or plotly is almost instantaneous.

**Comment by ian-r-rose** [comment]
I think that @ellisonbg and I also saw that with the fasta renderer. It seems like the msa package has some performance issues.

**Comment by gnestor** [comment]
It's strange because it's not running any of the widget code during this 2-4s delay, meaning that if I set breakpoints in the widget code, it won't break until after that 2-4s delay, then when I resume execution it switches tabs immediately. So I'm not sure if it's the msa library that is causing this...

The performance profile for switching between tabs with fasta rendered:

image

As you can see, the first 3s are spent doing phosphor messaging stuff. `MimeDocument._render` takes 634ms total, 573ms of which is `msa.render`.

Compared to switching between tabs with geojson rendered:

image

@sccolbert Any idea what is going on here? I saved the profile to disk so I can share with you if you want to check it out.

**Comment by gnestor** [comment]
Ping @sccolbert

**Pull request merged**
