### PR TITLE
Use Yarn Workspaces

### PR DESCRIPTION
**Pull request by blink1073**
Switches over to using yarn workspaces following https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/.  cf https://github.com/jupyterlab/jupyterlab/pull/3168

```bash
$ git clean -dfx && yarn && yarn
Removing .ipynb_checkpoints/
Removing node_modules/
Removing packages/.DS_Store
Removing packages/fasta-extension/lib/
Removing packages/fasta-extension/node_modules/
Removing packages/geojson-extension/.ipynb_checkpoints/
Removing packages/geojson-extension/lib/
Removing packages/geojson-extension/node_modules/
Removing packages/json-extension/
Removing packages/katex-extension/.DS_Store
Removing packages/katex-extension/lib/
Removing packages/katex-extension/node_modules/
Removing packages/plotly-extension/lib/
Removing packages/plotly-extension/node_modules/
Removing packages/vdom-extension/
Removing packages/vega3-extension/
yarn install v1.2.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 8.46s.
yarn install v1.2.1
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.62s.
```

### CODE REVIEW

**Comment by blink1073** [comment]
Also switches to independent versioning because the mime renderers will move at a different pace than the standard extensions.

**Comment by blink1073** [comment]
We have to temporarily  use `npm.org` as our registry pending https://github.com/lerna/lerna/issues/688

**Comment by gnestor** [comment]
@blink1073 Should we wait to merge this until https://github.com/lerna/lerna/issues/688 is resolved?

**Comment by blink1073** [comment]
No, we can remove the `.yarnrc` entry when that issue is resolved.

**Comment by gnestor** [comment]
I'm having trouble testing this with jupyterlab after lab switched over to yarn. I described my issue at https://github.com/jupyterlab/jupyterlab/issues/3279. I'm going to hold off merging this until I can get it to work.

**Comment by gnestor** [comment]
🍻

**Pull request merged**
