### PR TITLE
Update for JLab 26

### PR DESCRIPTION
**Pull request by blink1073**
Note that these new file types can also supply icons now using `iconClass`.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
This would be great!

**Comment by gnestor** [comment]
Thanks @blink1073!

**Comment by blink1073** [comment]
@gnestor, heads up I published the new geojson and json packages.  I didn't use lerna because of the plotly issue.

**Comment by gnestor** [comment]
Thanks!

**Pull request merged**
