### PR TITLE
Allow plotly.js to set its own height

### PR DESCRIPTION
**Pull request by gnestor**
Closes https://github.com/jupyterlab/jupyter-renderers/issues/38

Test notebook: https://gist.github.com/gnestor/661f4b4a631ad810b377a911398d8753

### CODE REVIEW

**Comment by dhirschfeld** [comment]
Excited about this as Plotly in JupyterLab is one of the marquee features I'm hoping to demo for our users!

**Comment by gnestor** [comment]
Ok, let's merge this and release a new version!

**Comment by gnestor** [comment]
Published!: https://www.npmjs.com/package/@jupyterlab/plotly-extension

**Comment by dhirschfeld** [comment]
I can confirm that the latest version is working great!

**Pull request merged**
