### PR TITLE
Upgrade to jupyterlab 1.0.0-alpha.3

### PR DESCRIPTION
**Pull request by gnestor**

### CODE REVIEW

**Comment by gnestor** [comment]
The [Travis build on master](https://travis-ci.org/jupyterlab/jupyter-renderers/builds/493340690) is failing and I'm not sure if it's because katex-extension and mathjax3-extension are out-of-date or canvas is failing node-gyp build. I guess we'll see after this build finishes...

**Comment by ian-r-rose** [comment]
Yeah, those will need to be updated a bit more, as they are note rendermime extensions. I think it should be enough to `s/JupyterLab/JupyterFrontEnd`

**Comment by gnestor** [comment]
Ya just caught that!

**Comment by ian-r-rose** [comment]
Thanks @gnestor!

**Pull request merged**
