### PR TITLE
Add watch to npm

### PR DESCRIPTION
**Pull request by domoritz**
This way I can develop without installing lerna globally.

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks for this!  It looks like the command should be `lerna run --parallel watch` based on this issue comment: https://github.com/lerna/lerna/issues/449#issuecomment-324837965

**Comment by blink1073** [comment]
(and don't worry about the Travis failure, we technically haven't set it up yet pending #49)

**Comment by domoritz** [comment]
@blink1073 Updated.
 
You can set travis to not build if there is no travis.yml file.

**Comment by blink1073** [comment]
Our scripts are just `watch` (not `build:watch`): https://github.com/jupyterlab/jupyter-renderers/blob/09872632fc6786d8ea3539b43269a1545b9ac2be/packages/geojson-extension/package.json#L31

**Comment by blink1073** [comment]
Thanks, toggled the setting.

**Comment by domoritz** [comment]
Thanks. Works now. 

screen shot 2017-10-17 at 15 44 32

**Comment by blink1073** [comment]
Cheers!

**Pull request merged**
