### PR TITLE
updated CI

### LINKED ISSUE #211: CI is failing
I'm seeing some consistent CI build failures but I don't understand what's causing them.

```
RemoveError: 'setuptools' is a dependency of conda and cannot be removed from conda's operating environment.
````
https://travis-ci.org/jupyterlab/jupyter-renderers/builds/563656110#L667

@scopatz

### PR DESCRIPTION
**Pull request by scopatz**
should fix #211

### CODE REVIEW

**Comment by scopatz** [comment]
yep @gnestor - this fixes the problem in #211

**Comment by gnestor** [comment]
Thanks so much @scopatz!! In laymen's terms, what does this change mean?

**Comment by scopatz** [comment]
"add_pip_as_python_dependency" means that Python depends on pip, which doesn't allow the solver to try to remove setuptools, pip, etc when updating Python.

"channel_priority: strict" [is how you are suppossed to use conda-forge](https://conda-forge.org/#about). It basically means that packages should be taken from the channels first.  For example, if defaults  has a higher version number or build number of a package than conda-forge, the lower version from conda-forge will still be used because channel priority matters the most.  Being "strict" prevents a lot of weird package & channel flip-flopping on updates and is overall more stable. It will (hopefully, eventually) become the default in conda itself.

**Comment by gnestor** [comment]
Great, thanks for the explanation!

**Pull request merged**
